ProgrammersHut/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from homepage import views
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from chat.sitemap import ChatSitemap
from support.sitemap import ContactoSitemap
from homepage.sitemap import HomepageSitemap
from login.sitemap import RegisterSitemap, LoginSitemap
from profiles.sitemap import ProfilesSitemap


sitemaps = {
    "chat": ChatSitemap,
    "contacto": ContactoSitemap,
    "index": HomepageSitemap,
    "register": RegisterSitemap,
    "login": LoginSitemap,
    "profiles": ProfilesSitemap,
}

urlpatterns = [
    path("accounts/", include("registration.backends.default.urls")),
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("", include("login.urls")),
    path("", views.index, name="index"),
    path("", include("chat.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("support.urls")),
    path("", include("amigos.urls")),
    path("", include("profiles.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("", include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    #import debug_toolbar

    #urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from chat import views
#from homepage import views as home_views

urlpatterns = [
    # path("chats", home_views.index, name="chats"),
    # path("chats/<str:room_name>/", views.room, name="room"),
    path("lobby", views.room, name="lobby"),
]

support/urls.py
from django.urls import path

from support import views
from .admin import AdminQuery

urlpatterns = [
    path("contacto", views.Contacto.as_view(), name="contacto"),
    path("admin/contacto/consulta", AdminQuery.exportar_conversacion, name="consulta"),
    path("faq", views.preguntas_frecuentes, name="faq"),
]

support/models.py
from django.db import models
from datetime import datetime
from django.utils.html import format_html
from ckeditor_uploader.fields import RichTextUploadingField

# The Consulta class is a model in a Python Django project that represents a consultation with a name,
# content, response status, email, and date, and has a method to display the status with different
# background colors.
class Consulta(models.Model):

    ANSWERED = "Contestada"
    NOT_ANSWERED = "No Contestada"
    IN_PROCESS = "En Proceso"

    STATUS = (
        (ANSWERED, "Contestada"),
        (NOT_ANSWERED, "No Contestada"),
        (IN_PROCESS, "En Proceso"),
    )

    nombre = models.CharField(max_length=50, blank=True, null=True)
    contenido = models.TextField(blank=False, null=False)
    estadoRespuesta = models.CharField(max_length=15, blank=True, choices=STATUS, default=NOT_ANSWERED)
    mail = models.EmailField(max_length=50, blank=True, null=True)
    fecha = models.DateField(default=datetime.now, blank=True, editable=True)

    
    def answer_status(self):
        if self.estadoRespuesta == self.ANSWERED:
            return format_html('<span style="background-color:#0a0; color: #fff; padding:5px;">{}</span>', self.estadoRespuesta, )
        elif self.estadoRespuesta == self.NOT_ANSWERED:
            return format_html('<span style="background-color:#a00; color: #fff; padding:5px;"">{}</span>', self.estadoRespuesta, )
        elif self.estadoRespuesta == self.IN_PROCESS:
            return format_html('<span style="background-color:#F0B203; color: #000; padding:5px;"">{}</span>', self.estadoRespuesta, )

# The `Respuesta` class is a model in a Python Django application that represents a response to a
# consultation, and it includes a method to update the state of the consultation when a response is
# created.
class Respuesta(models.Model):

    consulta = models.ForeignKey(Consulta(), blank=True, null=True, on_delete=models.CASCADE)
    contenido = models.TextField(blank=False, null=False)
    fecha = models.DateField(default=datetime.now, blank=True, editable=True)

    def create_message(self):

        changeEstadoConsulta = Consulta.objects.get(id=self.consulta.id)
        changeEstadoConsulta.estadoRespuesta = "Contestada"
        changeEstadoConsulta.save()

    def save(self, *args, **kwargs):
        self.create_message()
        force_update = False
        if self.id:
            force_update = True
        super(Respuesta, self).save(force_update=force_update)

# The class "PreguntasFrecuentes" represents frequently asked questions with fields for the question,
# description, and content.
class PreguntasFrecuentes(models.Model):
    pregunta = models.CharField(max_length=160, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    contenido = RichTextUploadingField(blank=True, null=True)

support/forms.py
from django import forms
from django.forms import ModelForm
from .models import Consulta
from captcha.fields import CaptchaField

# The `FormQuery` class is a model form that includes a captcha field and is used to send an email
# with the form data.
class FormQuery(ModelForm):

    captcha = CaptchaField()

    class Meta:
        # Model I'll be using in this form
        model = Consulta
        fields = [
            "nombre",
            "contenido",
            "mail",
        ]

    def send_email(self):
        # send email using the self.cleaned_data dictionary

        name = self.cleaned_data["nombre"]
        content = self.cleaned_data["contenido"]
        mail = self.cleaned_data["mail"]

        print("Enviando datos")
        print(name, content, mail)

support/views.py
from django.shortcuts import render
from .forms import FormQuery
from django.views.generic import FormView
from django.contrib import messages
from support.models import PreguntasFrecuentes



# The Contacto class is a FormView that handles form submission, saves the form data, sends an email,
# and redirects to a success URL.
class Contacto(FormView):

    template_name = "support/contacto.html"
    form_class = FormQuery
    success_url = "/"

    def form_valid(self, form):
        # Si el formulario es valido, hace esto:
        # 1) Llama al método save() que se encuentra dentro del formulario
        # 2) Redirecciona
        form.save()
        messages.success(self.request,"Gracias por su consulta. Nos pondremos en contacto con usted lo antes posible.")
        form.send_email()
        return super().form_valid(form)
    
def preguntas_frecuentes(request):
    """
    The function "preguntas_frecuentes" retrieves all the frequently asked questions from the database
    and renders them in the "faq.html" template.
    
    :param request: The request parameter is an object that represents the HTTP request made by the
    user. It contains information such as the user's browser, IP address, and any data sent with the
    request
    :return: a rendered HTML template called "faq.html" with a context variable "params" that contains
    all the objects from the "PreguntasFrecuentes" model.
    """
    params = {}
    params["preguntas"] = PreguntasFrecuentes.objects.all()

    return render(request, "support/faq.html", params)

templates/support/contacto.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% load static %}

{% block main %}
<div class="container-fluid" itemscope itemtype="http://schema.org/ContactPage">
    <div class="row" style="padding-top:20px;">   
        <div class="col-10 col-md-3 text-light mx-auto" style="padding-bottom:15px;">
            <h1 class="h1" itemprop="name">Contacto</h1>    
            <form id="contact" method="post" class="col-sm-12" itemprop="potentialAction" itemscope itemtype="http://schema.org/CommunicateAction">{% csrf_token %} 		
                <div class="col-12 form-group" >
                    {{ form }}
                </div> 
                <div class="row justify-content-between">
                    <div class="col-4"></div>
                    <div class="col-12 mt-2 mb-4">
                        <button type="submit"  class=" col-12 btn btn-danger">Enviar</button>
                    </div>
                </div>                        
            </form>
        </div>    
    </div>
</div>  
{% endblock %}
{% block moreJs %}
<script>
    let nombre = $("#id_nombre")
    let descripcion = $("#id_descripcion")
    let mail = $("#id_mail")
    let captcha = $("#id_captcha_1")

    nombre.attr("placeholder", "Nombre");
    descripcion.attr("placeholder", "Descripcion");
    mail.attr("placeholder", "Mail");
    captcha.attr("placeholder", "Captcha");

    nombre.addClass("form-control mb-1");
    descripcion.addClass("form-control mb-1");
    mail.addClass("form-control mb-1");
    captcha.addClass("form-control mb-1");
</script>
{% endblock %}

templates/support/faq.html
{% extends "layout.html" %}
{% load static %}
{% block title %}FAQ{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-12 pt-5 pb-5 text-light">
            {% for pregunta in preguntas %}
                <h1 class="h1">{{pregunta.pregunta}}</h1>
                <p class="text-secondary">{{pregunta.descripcion}}</p>
                {{pregunta.contenido|safe}}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}